import PDFDocument from 'pdfkit';
import { Parser } from 'json2csv';
import * as XLSX from 'xlsx';
import { PassThrough } from 'stream';

/**
 * Generate PDF report buffer
 */
export const generatePDFReport = (data, options = {}) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 50,
      size: 'A4',
      info: {
        Title: options.title || 'Attendance Report',
        Author: 'FRAMS - AI Attendance System',
        CreationDate: new Date(),
      },
    });

    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Colors
    const PRIMARY = '#1e40af';
    const SECONDARY = '#374151';
    const ACCENT = '#dc2626';
    const LIGHT_GRAY = '#f3f4f6';
    const TEXT = '#111827';

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill(PRIMARY);
    doc.fill('white').fontSize(22).font('Helvetica-Bold').text('FRAMS', 50, 20);
    doc.fontSize(12).font('Helvetica').text('AI-Powered Attendance Management System', 50, 48);

    // Title
    doc.fill(TEXT).fontSize(18).font('Helvetica-Bold').text(options.title || 'Attendance Report', 50, 100);
    doc.fontSize(10).font('Helvetica').fill(SECONDARY).text(`Generated: ${new Date().toLocaleString('en-IN')}`, 50, 125);

    if (options.generatedBy) {
      doc.text(`Generated by: ${options.generatedBy}`, 50, 140);
    }

    doc.moveDown(2);

    // Summary section
    if (data.summary) {
      doc.fill(TEXT).fontSize(14).font('Helvetica-Bold').text('Summary', 50, doc.y);
      doc.moveDown(0.5);
      doc.rect(50, doc.y, doc.page.width - 100, 1).fill('#e5e7eb');
      doc.moveDown(0.5);

      const summaryItems = Object.entries(data.summary);
      summaryItems.forEach(([key, value]) => {
        const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
        doc.fontSize(10).font('Helvetica').fill(SECONDARY).text(`${label}:`, 50, doc.y, { continued: true });
        doc.fill(TEXT).font('Helvetica-Bold').text(` ${value}`);
      });

      doc.moveDown(1.5);
    }

    // Records table
    if (data.records && data.records.length > 0) {
      doc.fill(TEXT).fontSize(14).font('Helvetica-Bold').text('Attendance Records', 50, doc.y);
      doc.moveDown(0.5);
      doc.rect(50, doc.y, doc.page.width - 100, 1).fill('#e5e7eb');
      doc.moveDown(0.5);

      const headers = Object.keys(data.records[0]);
      const colWidth = (doc.page.width - 100) / Math.min(headers.length, 6);
      const displayHeaders = headers.slice(0, 6);

      // Table header
      const headerY = doc.y;
      doc.rect(50, headerY, doc.page.width - 100, 20).fill(PRIMARY);
      displayHeaders.forEach((h, i) => {
        doc.fill('white').fontSize(8).font('Helvetica-Bold')
          .text(h.toUpperCase().slice(0, 15), 55 + i * colWidth, headerY + 5, { width: colWidth - 5, lineBreak: false });
      });

      let rowY = headerY + 22;
      let rowCount = 0;

      data.records.forEach((record, idx) => {
        // Check for page overflow
        if (rowY + 20 > doc.page.height - 60) {
          doc.addPage();
          rowY = 60;
        }

        const bgColor = idx % 2 === 0 ? 'white' : LIGHT_GRAY;
        doc.rect(50, rowY, doc.page.width - 100, 18).fill(bgColor);

        displayHeaders.forEach((h, i) => {
          const val = record[h] !== undefined && record[h] !== null ? String(record[h]).slice(0, 20) : '-';
          const color = h.toLowerCase().includes('status') && val.toLowerCase() === 'absent' ? ACCENT : TEXT;
          doc.fill(color).fontSize(8).font('Helvetica')
            .text(val, 55 + i * colWidth, rowY + 4, { width: colWidth - 5, lineBreak: false });
        });

        rowY += 20;
        rowCount++;
      });

      doc.moveDown(1);
      doc.y = rowY + 10;
      doc.fill(SECONDARY).fontSize(9).font('Helvetica').text(`Total Records: ${data.records.length}`, 50, doc.y);
    }

    // Footer
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fill('#9ca3af').fontSize(8)
        .text(`Page ${i + 1} of ${pageCount} | FRAMS Attendance System | Confidential`, 50, doc.page.height - 40, {
          align: 'center',
          width: doc.page.width - 100,
        });
    }

    doc.end();
  });
};

/**
 * Generate CSV report buffer
 */
export const generateCSVReport = (records, fields = null) => {
  if (!records || records.length === 0) {
    return Buffer.from('No data available\n');
  }

  const opts = {
    fields: fields || Object.keys(records[0]),
    header: true,
    quote: '"',
    delimiter: ',',
  };

  const parser = new Parser(opts);
  const csv = parser.parse(records);
  return Buffer.from(csv, 'utf-8');
};

/**
 * Generate Excel report buffer
 */
export const generateExcelReport = (data, options = {}) => {
  const wb = XLSX.utils.book_new();

  // Summary sheet
  if (data.summary) {
    const summaryData = Object.entries(data.summary).map(([key, value]) => ({
      Metric: key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase()),
      Value: value,
    }));

    const summarySheet = XLSX.utils.json_to_sheet(summaryData);
    summarySheet['!cols'] = [{ wch: 30 }, { wch: 20 }];
    XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');
  }

  // Records sheet
  if (data.records && data.records.length > 0) {
    const recordsSheet = XLSX.utils.json_to_sheet(data.records);

    // Auto-width columns
    const headers = Object.keys(data.records[0]);
    recordsSheet['!cols'] = headers.map((h) => ({
      wch: Math.max(h.length, 15),
    }));

    XLSX.utils.book_append_sheet(wb, recordsSheet, 'Attendance Records');
  }

  // Charts data sheet
  if (data.charts) {
    const chartsSheet = XLSX.utils.json_to_sheet(data.charts);
    XLSX.utils.book_append_sheet(wb, chartsSheet, 'Charts Data');
  }

  // Metadata sheet
  const metaSheet = XLSX.utils.json_to_sheet([
    { Key: 'Report Title', Value: options.title || 'Attendance Report' },
    { Key: 'Generated At', Value: new Date().toLocaleString('en-IN') },
    { Key: 'Generated By', Value: options.generatedBy || 'System' },
    { Key: 'System', Value: 'FRAMS - AI Attendance Management System' },
    { Key: 'Total Records', Value: data.records?.length || 0 },
  ]);
  metaSheet['!cols'] = [{ wch: 20 }, { wch: 40 }];
  XLSX.utils.book_append_sheet(wb, metaSheet, 'Metadata');

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx', compression: true });
};
